data_config: "config/gpu/runs/trim/data_config.yaml"
parent_path: "config/gpu/runs/training_parent.yaml"

skip_trained: True

databases: ['citynet2', "nips4b2", "NABS2", "arctic_complete2"]

id: "_{learning_rate}_{n_epochs}"
id_prefixes:
  learning_rate: "lr-"
  n_epochs: "epochs-"

n_epochs: 15
learning_rate: 0.01
pixels_per_sec: 200
num_dense_units: 128
num_filters: 64
wiggle_room: 10
early_stopping:
  patience: 4
  min_delta: 0.005

scenarios:
  - name: "DLBD"
    id: "_d1-{num_dense_i}_d2"
    class: "dlbd.models.dlbd.DLBD"
    spectrogram_overlap: 0.75
    random_start: True
    regularizer:
      type: "l2"
      value: 0.001
    time_mask:
      value: 20
    freq_mask:
      value: 50
    num_dense_units: [32, 64, 128, 256]
    num_dense_units2: [None, 32, 64, 128]



