
data_config: "config/gpu/runs/data_config.yaml"
save_results: True #True

###############
## Detectors ##
###############

evaluators_options:
  do_PR_curve: False
  plots: "overlap_duration_bar; detected_tags"

evaluators: 
    - type: "standard"
      activity_threshold: 0.92
      min_duration: 0.4
      end_threshold: 0.15
      dtc_threshold: 0
      gtc_threshold: 0
      scenarios:
        min_duration: 0.1
      # scenarios:
      #   buffer:
      #     start: 0
      #     end: 2
      #     step: 0.2
    #   isolate_events: True
      # plot_tag_repartition: False
      PR_curve:
        variable: activity_threshold
        values:
          start: 0.02
          end: 0.10
          step: 0.05
    - type: subsampling
      sample_step: 1
      activity_threshold: 0.6
    #   PR_curve:
    #     variable: activity_threshold
    #     values:
    #       start: 0
    #       end: 0.98
    #       step: 0.02
    #   # event_method: "average"
    #   # tag_method: "proportion"
    #   gtc: 0.3
  # - type: "subsampling"
  #   gtc: 0.3
  #   scenarios:
  #     sample_step: [0.5, 1]
  #     event_threshold: [0.5, 0.95]
  #     event_method: ["average", "presence"]


###############
## Databases ##
###############

databases_options:
  class_type: "biotic"
  spectrogram:
    n_mels: 32
    sample_rate: "original"
    hop_length: 1024

databases:
  # - name: citynet_small
    # scenarios:
    #     spectrogram:
    #       sample_rate: ["original", 22050]
  - name: citynet
  - name: arctic_complete
  - name: nips4b
  - name: NABS
#  - name: citynet
  # - name: nips4b
    # scenarios:
    #     spectrogram:
    #       sample_rate: ["original", 22050]
