parent_path: "config/gpu/runs/training_parent.yaml"

skip_trained: True

id: "_{learning_rate}_{n_epochs}"
id_prefixes:
  learning_rate: "lr-"
  n_epochs: "epochs-"

n_epochs: 15
learning_rate: 0.01
pixels_per_sec: 200

scenarios:
  - name: "DLBDL_CiNiNaA"
    class: "dlbd.models.dlbd.DLBDLite"
  - name: "DLBDLDrop_CiNiNaA"
    class: "dlbd.models.dlbd.DLBDLiteDrop"
    n_epochs: 50
  - name: "DLBDLBN_CiNiNaA"
    class: "dlbd.models.dlbd.DLBDLiteBN"
  - name: "DLBDLBNrelu"
    class: "dlbd.models.dlbd.DLBDLiteBNrelu"
  - name: "DLBDDBNrelu"
    class: "dlbd.models.dlbd.DLBDDenseBNRelu"
    num_dense_units: 256
    num_dense_units2: 32
  - name: "DLBDDDroprelu"
    class: "dlbd.models.dlbd.DLBDDenseDropRelu"
    num_dense_units: 256
    num_dense_units2: 32






