data_config: "config/gpu/runs/22_checked_all/data_config.yaml"
parent_path: "config/gpu/runs/evaluation_parent.yaml"

models_options:
  spectrogram_overlap: 0.95
  repredict: False
  smooth_predictions: True

id: smoothed

evaluators_options:
  draw_plots: False
  phenology_databases: ["full_summer_final"]
  presence_databases: ["arctic_checked_all"]
  plots: ["distances", "pr_curve", "roc", "separate_distances"] #"separate_distances", "roc"

evaluators:
  - type: "phenology"
    method: "standard"
    activity_threshold: 0.9
    min_duration: 0.4
    end_threshold: 0.5
    dtc_threshold: 0
    gtc_threshold: 0
    daily_aggregation: "sum"
  - type: standard
    activity_threshold: 0.9
    min_duration: 0.4
    end_threshold: 0.5
    dtc_threshold: 0
    gtc_threshold: 0
  - type: direct
    activity_threshold: 0.7
  - type: presence
    method: "standard"
    activity_threshold: 0.92
    min_duration: 0.4
    end_threshold: 0.5
    dtc_threshold: 0
    gtc_threshold: 0
  - type: presence
    method: direct
    activity_threshold: 0.7


databases:
  - name: citynet_final
  - name: full_summer_final
  - name: nips4b_final
  - name: arctic_complete_final