data_config: "config/gpu/runs/trim/data_config.yaml"
parent_path: "config/gpu/runs/evaluation_parent.yaml"

evaluators_options:
  draw_plots: False

evaluators:
  - type: "standard"
    scenarios:
      activity_threshold: [0.5, 0.6, 0.9]
      min_duration: [0.05, 0.1, 0.2, 0.4]
      end_threshold: [0.15, 0.3, 0.]
    dtc_threshold: 0
    gtc_threshold: 0
  - type: subsampling
    sample_step: 1
    activity_threshold: 0.6