data_config: "config/gpu/runs/trim/data_config.yaml"
parent_path: "config/gpu/runs/training_parent.yaml"

skip_trained: True

databases: ['citynet2', "nips4b2", "NABS2", "arctic_complete2"]

id: "_{learning_rate}_{n_epochs}"
id_prefixes:
  learning_rate: "lr-"
  n_epochs: "epochs-"

n_epochs: 15
learning_rate: 0.01
pixels_per_sec: 200
num_dense_units: 128
num_filters: 64
wiggle_room: 10
early_stopping:
  patience: 3

scenarios:
  - name: "DLBDL_control_dense128_filt64_pps200_lr01_wr10"
    class: "dlbd.models.dlbd.DLBD"
    time_mask: False
    freq_mask: False
  - name: "DLBDL_random_overlap"
    class: "dlbd.models.dlbd.DLBD"
    id: "{spectrogram_overlap}"
    random_start: True
    time_mask: False
    freq_mask: False
    spectrogram_overlap: [0.75, 0.8, 0.85, 0.95]
  - name: "DLBDL_reg"
    class: "dlbd.models.dlbd.DLBD"
    id: "type{regularizer--type}_value{regularizer--value}"
    time_mask: False
    freq_mask: False
    regularizer:
      type: ["l2", "l1", "l1l2"]
      value: [0.001, 0.01]
  - name: "DLBDL_mask"
    class: "dlbd.models.dlbd.DLBD"
  - name: "DLBDL_mask_reg"
    class: "dlbd.models.dlbd.DLBD"
    id: reg-type{regularizer--type}"
    regularizer:
      type: "l2"
      value: 0.001





