data_config: "config/gpu/runs/trim/data_config.yaml"
parent_path: "config/gpu/runs/training_parent.yaml"

skip_trained: True

databases: ['citynet2', "nips4b2", "NABS2", "arctic_complete2"]

id: "_{learning_rate}_{n_epochs}"
id_prefixes:
  learning_rate: "lr-"
  n_epochs: "epochs-"

n_epochs: 15
learning_rate: 0.01
pixels_per_sec: 170
num_dense_units: 128
num_filters: 64
wiggle_room: 10
early_stopping:
  patience: 2
  min_delta: 0.005

scenarios:
  - name: "DLBDL_control_dense128_filt64_pps200_lr01_wr10"
    id: "pps{pixels_per_sec}"
    class: "dlbd.models.dlbd.DLBD"
    time_mask: False
    freq_mask: False
  - name: "DLBDL_random_overlap"
    class: "dlbd.models.dlbd.DLBD"
    id: "pps{pixels_per_sec}_{spectrogram_overlap}"
    random_start: True
    time_mask: False
    freq_mask: False
    spectrogram_overlap: [0.75, 0.8, 0.85, 0.95]
  - name: "DLBDL_reg"
    class: "dlbd.models.dlbd.DLBD"
    id: "pps{pixels_per_sec}_type{regularizer--type}_value{regularizer--value}"
    time_mask: False
    freq_mask: False
    spectrogram_overlap: 0.75
    random_start: True
    regularizer:
      type: ["l2", "l1", "l1l2"]
      value: [0.001, 0.01]
  - name: "DLBDL_mask"
    class: "dlbd.models.dlbd.DLBD"
  - name: "DLBDL_mask_reg"
    class: "dlbd.models.dlbd.DLBD"
    id: "pps{pixels_per_sec}_reg-type{regularizer--type}"
    regularizer:
      type: "l2"
      value: 0.001
  - name: "DLBDL_mask_reg"
    class: "dlbd.models.dlbd.DLBD"
    id: "pps{pixels_per_sec}reg-type{regularizer--type}_overlap{}_tm{time_mask--value}_fm{freq_mask--value}"
    regularizer:
      type: "l2"
      value: 0.001
    spectrogram_overlap: 0.75
    random_start: True
    time_mask:
      value: [10, 20, 30]
    freq_mask:
      value: [20, 30, 50, 70]





