#* All path can be relative to the root_dir or complete
# root_dir: other dirs will be relative to this one
data_dir: 'wavs'
tags_dir: 'tags'
training_dir: 'training'
validation_dir:  'validation'
test_dir: 'test'
dest_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/datasets'
save_intermediate: False

use_subfolders: ["spectrogram"]
subfolders:
  - type: spectrogram
    options: ["sample_rate", "type", "n_fft", "win_length", "hop_length"]

data_extensions:
  - ".wav"
  - ".WAV"
recursive: True

#* Tags files options
tags:
  suffix: "-sceneRect.csv"
  columns:
    Label: "tag"
    Related: "related"
    LabelStartTime_Seconds: "tag_start"
    LabelEndTime_Seconds: "tag_end"
    overlap: "overlap"
    background: "background"
    noise: "noise"
    Filename: "file_name"
  columns_type:
    overlap: "str"
  with_data: False
  print_missing_classes: True


databases:
  #* All options found in data can be overriden in each iteration. If not found, default values
  #* from data will be used
    - name: 'citynet'
      root_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/raw/CityNet'
      split:
        validation: 0.2
    - name: 'arctic'
      root_dir: "/mnt/win/UMoncton/OneDrive - Université de Moncton/Data/Reference/Arctic/Tommy"
      data_dir: "/mnt/win/UMoncton/OneDrive - Université de Moncton/Data/Reference/Arctic/Tommy"
      tags:
        with_data: True
      # overwrite: False
      # generate_file_lists: True
      #* split: Defines proportion of data to set aside for test and validation datasets.
      #* If provided, first the test dataset is set aside, then the remaining data is split into
      #* training and validation datasets.
      #* Overrides training_dir/validation_dir. Set to false or 0 to avoid using it in a database
      split:
        test: 0.2
        validation: 0.2

    - name: 'arctic_complete'
      root_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/Arctic_complete'
      data_dir: "/mnt/win/UMoncton/OneDrive - Université de Moncton/Data/Reference/Arctic/Complete"
      tags:
        with_data: True
      overwrite: False
      # generate_file_lists: True
      #* split: Defines proportion of data to set aside for test and validation datasets.
      #* If provided, first the test dataset is set aside, then the remaining data is split into
      #* training and validation datasets.
      #* Overrides training_dir/validation_dir. Set to false or 0 to avoid using it in a database
      split:
        test: 0.2
        validation: 0.2
    - name: 'nips4b'
      root_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/raw/nips4b'
      data_dir: "/mnt/win/UMoncton/Doctorat/data/dl_training/raw/nips4b/wavs"
      tags_dir: "/mnt/win/UMoncton/Doctorat/data/dl_training/raw/nips4b/tags"
      split:
        validation: 0.2
        test: 0.2
      tags:
        type: "nips4b"
    - name: 'NABS'
      root_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/NABS'
      data_dir: '/mnt/win/UMoncton/OneDrive - Université de Moncton/Data/Reference/generated/NABS/2'
      tags:
        with_data: True
        suffix: "_tags.csv"
        columns:
          tag: "tag"
          start: "tag_start"
          end: "tag_end"
      split:
        validation: 0.2
        test: 0.2
    - name: 'full_summer1'
      root_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/raw/full_summer_subset1/'
      data_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/raw/full_summer_subset1/'
      db_types: ["test"]
      overwrite: False
      
      tags:
        with_data: True
    - name: 'ENAB'
      root_dir: '/home/vin/Doctorat/data/dl_training/raw/ENAB'
      data_dir: '/home/vin/Doctorat/data/dl_training/raw/ENAB'
      db_types: ["test"]
      overwrite: False
      tags:
        print_missing_classes: True
        filter_classes: False
        with_data: True
        suffix: ".Table.1.selections.txt"
        columns:
          Species: "tag"
          "Begin Time (s)": "tag_start"
          "End Time (s)": "tag_end"
      

spectrogram:
  type: "mel"
  n_mels: 32
  n_fft: 512
  sample_rate: "original" # For no resampling: remove option or set to original

class_type: "biotic"
classes_file: "resources/classes.csv"