data_config: "config/gpu/global_eval/data_config.yaml"
parent_path: "config/gpu/global_eval/evaluation_parent.yaml"

evaluation_dir: "/home/sylvain/data/results/global_eval/evaluation"

models_options:
  spectrogram_overlap: 0.95
  reclassify: False

evaluators_options:
  draw_plots: False
  phenology_databases: ["full_summer1"]

evaluators:
  - type: "phenology"
    method: "standard"
    activity_threshold: 0.9
    min_duration: 0.1
    end_threshold: 0.15
    dtc_threshold: 0
    gtc_threshold: 0
  - type: phenology
    method: subsampling
    sample_step: 1
    event_method: "activity_max"
    activity_threshold: 0.5
  - type: phenology 
    method: citynet
    activity_threshold: 0.5
  - type: "standard"
    activity_threshold: 0.9
    min_duration: 0.1
    end_threshold: 0.15
    dtc_threshold: 0
    gtc_threshold: 0
  - type: subsampling
    sample_step: 1
    event_method: "activity_max"
    activity_threshold: 0.5
  - type: citynet
    activity_threshold: 0.5

databases:
  - name: citynet2
  - name: full_summer1
  - name: nips4b2

models: []