data_config: "config/gpu/runs/unbalanced2/data_config.yaml"
parent_path: "config/gpu/runs/training_parent.yaml"

skip_trained: True

databases: ['citynet2', "nips4b2", "NABS2", "arctic_complete3"]

n_epochs: 50
learning_rate: 0.01
wiggle_room: 10
early_stopping:
  min_delta: 0.002
  patience: 8
  restore_best_weights: false
spectrogram_overlap: 0.75
random_start: True
time_mask: True
freq_mask: True
dilation_rate: [[1, 2], 1]
training_balanced: False
wriggle_room: 3 #[3, 5, 10]
batch_size: 256 #[256, 128, 64, 32]
num_filters: 128
num_dense_units: 512
num_dense_units2: 256
pixels_per_sec: 100

scenarios:
  - name: "DLBD_unbal"
    class: "dlbd.models.dlbd.DLBD"




