A: 0.001
B: 10.0
CLASSNAME: biotic
CONV_FILTER_WIDTH: 4
DO_AUGMENTATION: 1
DO_BATCH_NORM: 1
ENSEMBLE_MEMBERS: 1
HWW_X: 10
HWW_Y: 10
LEARNING_RATE: 0.001
LEARN_LOG: 0
MAX_EPOCHS: 5
NUM_DENSE_UNITS: 512
NUM_FILTERS: 128
SPEC_TYPE: mel
WIGGLE_ROOM: 5
spec_height: 32
A: 0.001
B: 10.0
CLASSNAME: biotic
conv_filter_width: 4
do_augmentation: 1
hww_x: 10
hww_y: 10
learning_rate: 0.001
learn_log: 0
max_epochs: 5
num_dense_units: 512
num_filters: 128
spec_type: mel
wiggle_room: 5
channels: 4