data_config: "config/gpu/runs/unbalanced/data_config.yaml"
parent_path: "config/gpu/runs/training_parent.yaml"

skip_trained: True

databases: ['citynet2', "nips4b2", "NABS2", "arctic_complete3"]

n_epochs: 50
learning_rate: 0.01
pixels_per_sec: 200
num_filters: 64
wiggle_room: 10
early_stopping:
  patience: 8
  min_delta: 0.002
  restore_best_weights: False
spectrogram_overlap: 0.75
random_start: True
num_dense_units: 128
num_dense_units2: 0
time_mask: True
freq_mask: True
dilation_rate: [[1, 2], 1]
training_balanced: False

scenarios:
  - name: "DLBD"
    id: "_wr{wriggle_room}_fil{num_filters}_d1-{num_dense_units}_d2-{num_dense_units2}_pps{pixels_per_sec}_bs{batch_size}"
    class: "dlbd.models.dlbd.DLBD"
    wriggle_room: 3 #[3, 5, 10]
    batch_size: 256 #[256, 128, 64, 32]
    num_filters: 128
    num_dense_units: 64
    num_dense_units2: 32
    pixels_per_sec: 200
  # - name: "DLBD"
  #   id: "_wr{wriggle_room}_fil{num_filters}_d1-{num_dense_units}_d2-{num_dense_units2}_pps{pixels_per_sec}_bs{batch_size}"
  #   class: "dlbd.models.dlbd.DLBD"
  #   wriggle_room: 3 #[3, 5, 10]
  #   batch_size: 256 #[256, 128, 64, 32]
  #   num_filters: [64, 128, 32]
  #   num_dense_units: [32, 64, 128, 256, 512]
  #   num_dense_units2: [0, 32, 64, 128, 256, 512]
  #   pixels_per_sec: [50, 100, 200]




