data_config: "config/gpu/runs/summary2/data_config.yaml"
parent_path: "config/gpu/runs/training_parent.yaml"

skip_trained: True

databases: ['citynet2', "nips4b2", "NABS2", "arctic_complete3"]

n_epochs: 50
learning_rate: 0.01
pixels_per_sec: 200
num_filters: 64
wiggle_room: 10
early_stopping:
  patience: 8
  min_delta: 0.002
  restore_best_weights: False
spectrogram_overlap: 0.75
random_start: True
num_dense_units: 128
num_dense_units2: 0
time_mask: True
freq_mask: True
dilation_rate: [[1, 2], 1]

scenarios:
  - name: "DLBDL64"
    id: "_wr{wriggle_room}_fil{num_filters}_d1-{num_dense_units}_d2-{num_dense_units2}_pps{pixels_per_sec}_bs{batch_size}"
    class: "dlbd.models.dlbd.DLBD"
    wriggle_room: 3
    batch_size: 256
    num_filters: 128
    num_dense_units: 64
    num_dense_units2: 32
    pixels_per_sec: 100
    databases_options:
      spectrogram:
        n_mels: 64
        n_fft: 1024
  - name: "DLBDL"
    id: "_wr{wriggle_room}_fil{num_filters}_d1-{num_dense_units}_d2-{num_dense_units2}_pps{pixels_per_sec}_bs{batch_size}"
    class: "dlbd.models.dlbd.DLBD"
    wriggle_room: [3, 5, 10]
    batch_size: [256, 128, 64]
    num_filters: [128, 64, 32]
    num_dense_units: 64
    num_dense_units2: 32
  - name: "DLBDL"
    id: "_wr{wriggle_room}_fil{num_filters}_d1-{num_dense_units}_d2-{num_dense_units2}_pps{pixels_per_sec}_bs{batch_size}"
    class: "dlbd.models.dlbd.DLBD"
    wriggle_room: [3, 5, 10]
    batch_size: [256, 128, 64]
    num_filters: [128, 64, 32]
    num_dense_units: 512
    num_dense_units2: 128
    pixels_per_sec: 100




