
data_config: "config/phenology/evaluation_data_config.yaml"
save_results: True #True

###########
## Paths ##
###########
predictions_dir: "results/phenology/predictions"
evaluation_dir: "results/phenology/evaluation"
models_options:
  spectrogram_overlap: 0.95
  # repredict: True
  # A: 0.05

evaluators_options:
  draw_plots: True
  plots: ["distances", "pr_curve", "roc", "separate_distances"] #"separate_distances", "roc"
  phenology_databases: ["full_summer1", "ENAB"]

evaluators:
  # - type: "standard"
  #   activity_threshold: 0.92
  #   min_duration: 0.4
  #   end_threshold: 0.15
  #   dtc_threshold: 0
  #   gtc_threshold: 0
  - type: "phenology"
    method: "citynet"
    activity_threshold: 0.7
    scenarios:
      remove_crows: [True, False]
  - type: citynet
    activity_threshold: 0.7
    # plots: ["separate_distances"]
  # - type: phenology
  #   method: standard
  #   scenarios:
  #     activity_threshold: 0.92
  #       # start: 0.5
  #       # end: 0.99
  #       # step: 0.1
  #     min_duration: 0.3
  #       # start: 0.1
  #       # end: 0.5
  #       # step: 0.1
  #     end_threshold:
  #       start: 0.1
  #       end: 0.6
  #       step: 0.05
  #     dtc_threshold: 0
  #     gtc_threshold: 0
      
  # - type: phenology
  #   method: citynet
  #   scenarios:
  #     activity_threshold: 
  #       start: 0.3
  #       end: 0.99
  #       step: 0.1

databases_options:
  class_type: "biotic"
  spectrogram:
    n_mels: 32
    n_fft: 512
    sample_rate: "original"

models_list_dir: "resources/models"

models_list_options:
  model_dir: "resources/models"
  ignore_parent_path: True
  batch_size: 64
  reclassify: True
  scenarios:
    spectrogram_overlap: 0.95

model_ids:
  - DLBD
  - citynet




databases:
  - name: full_summer1
  - name: ENAB
  - name: citynet
  - name: nips4b