
data_config: "config/phenology/evaluation_data_config.yaml"
save_results: True #True

###########
## Paths ##
###########
predictions_dir: "results/predictions"
evaluation_dir: "results/evaluation"
models_options:
  spectrogram_overlap: 0.95
  reclassify: False
  # A: 0.05

evaluators_options:
  draw_plots: True
  plots: ["distances"]
  phenology_databases: ["full_summer1"]

evaluators:
  - type: "phenology"
    method: "standard"
    activity_threshold: 0.9
  #   min_duration: 0.1
  #   end_threshold: 0.3
  #   dtc_threshold: 0.3
  #   gtc_threshold: 0.1
  - type: "phenology"
    method: "citynet"
    event_threshold: 0.6
  - type: subsampling
    sample_step: 1
  #   event_method: "activity_max"
  #   activity_threshold: 0.6
  # - type: citynet
  #   activity_threshold: 0.5

databases_options:
  class_type: "biotic"
  spectrogram:
    n_mels: 32
    n_fft: 512
    sample_rate: "original"

models_list_dir: "resources/models"

model_ids:
  # - "DLBDL_dl1-2_1_pat8_restoreFalse"
  # - "DLBDL_dl1-2_1_pat8_restoreTrue_delta0.002"
  # - "DLBDL_dl1-2_1_pat8_restoreFalse_delta0.002"
  # - "DLBDL_noes_lr-0.01_epochs-50"
  # - "DLBDL_replicate_2_lr-0.01_epochs-50"
  # - "DLBDL_replicate_1_lr-0.01_epochs-50"
  # - "DLBDL_dl1-2_1_pat5_restoreTrue_delta0.002"
  # - "DLBDL_dl1-2-1-2"
  # - "DLBDL_pat8_delta0.002"
  # - "DLBDL_pat5_delta0"
  # - "DLBDL_replicate_6_regl2_lr-0.01_epochs-50"
  # - "DLBDL_wr3_fil128_d1-64_d2-32_pps200_bs256"
  # - "DLBDL_wr3_fil64_d1-512_d2-256_pps100_bs256"
  - DLBD




databases:
  # - name: citynet_small
    # scenarios:
    #     spectrogram:
    #       sample_rate: ["original", 22050]
  # - name: arctic
  - name: full_summer1
  # - name: citynet
  # - name: nips4b
    # scenarios:
    #     spectrogram:
    #       sample_rate: ["original", 22050]