data_config: "config/gpu/runs/trim/data_config.yaml"
parent_path: "config/gpu/runs/evaluation_parent.yaml"

models_options:
  spectrogram_overlap: 0.95
  reclassify: True

evaluators_options:
  draw_plots: False

evaluators:
  - type: "standard"
    scenarios:
      # activity_threshold: [0.6, 0.7, 0.8, 0.9]
      activity_threshold: 0.9
      min_duration: [0.1, 0.2, 0.3, 0.4]
      end_threshold: 0.15
    dtc_threshold: 0
    gtc_threshold: 0
  - type: subsampling
    scenarios:
      sample_step: [0.15, 0.5, 1]
      event_method: ["activity_max", "activity_average"]
      activity_threshold: [0.5, 0.7, 0.9]