data_config: "config/gpu/runs/trim/data_config.yaml"
parent_path: "config/gpu/runs/training_parent.yaml"

skip_trained: True

databases: ['citynet2', "nips4b2", "NABS2", "arctic_complete2"]

id: "_{learning_rate}_{n_epochs}"
id_prefixes:
  learning_rate: "lr-"
  n_epochs: "epochs-"

n_epochs: 15
learning_rate: 0.01
pixels_per_sec: 200
num_filters: 64
wiggle_room: 10
early_stopping:
  patience: 4
  min_delta: 0.004
spectrogram_overlap: 0.75
random_start: True
regularizer:
  type: "l2"
  value: 0.001
time_mask:
  value: 20
freq_mask:
  value: 50
num_dense_units: 128

scenarios:
  - name: "DLBDL_original_nomask"
    id: "_patience{early_stopping--patience}_overlap{spectrogram_overlap}"
    class: "dlbd.models.dlbd.DLBD"
    spectrogram_overlap: [0.75, 0.85, 0.95]
    time_mask: False
    freq_mask: False
    early_stopping:
      patience: [2, 4]
      min_delta: 0.005
  - name: "DLBDL_original_mask"
    id: "_patience{early_stopping--patience}"
    class: "dlbd.models.dlbd.DLBD"
    early_stopping:
      patience: [2, 4]
      min_delta: 0.005
  - name: "DLBD_3x3"
    id: "_dil{dilation_rate}"
    class: "dlbd.models.dlbd.DLBD"
    dilation_rate: [[1,2], [2, 3]]
    conv_filter_width: 3
    conv_filter_height: 3
  - name: "DLBD_3x3x2"
    class: "dlbd.models.dlbd.DLBD"
    id: "_dil{dilation_rate}"
    dilation_rate: [[1,2], [2, 3]]
    conv_filter_width: 3
    conv_filter_height: 3
    conv2_filter_width: 3
    conv2_filter_height: 3
  - name: "DLBD_c2-3x3"
    id: "_dil{dilation_rate}"
    class: "dlbd.models.dlbd.DLBD"
    spectrogram_overlap: 0.75
    random_start: True
    dilation_rate: [[1,1], [1,2]]
    conv2_filter_width: 3
    conv2_filter_height: 3
  # - name: "DLBD_dilc1"
  #   id: "_d1-{num_dense_units}_d2-{num_dense_units2}_dil-{dilation_rate}"
  #   class: "dlbd.models.dlbd.DLBD"
  #   spectrogram_overlap: 0.75
  #   random_start: True
  #   dilation_rate: [[2, 2]]
  #   conv_filter_width: 3
  #   conv_filter_height: 16
  #   conv2_filter_width: 3
  #   conv2_filter_height: 3
  - name: "DLBD_input_width"
    id: "_pps{pixels_per_second}_iw{input_width}"
    class: "dlbd.models.dlbd.DLBD"
    spectrogram_overlap: 0.75
    random_start: True
    input_width: [50, 100, 150]
    num_dense_units: 128



