
data_config: "config/data/data_config.yaml"
save_results: True #True

###########
## Paths ##
###########

###############
## Detectors ##
###############

evaluators_options:
  do_PR_curve: False
  plots: ["overlap_duration_bar", "detected_tags"]
  draw_plots: True
  plots: ["distances"]
  phenology_databases: ["full_summer1"]

evaluators: 
    - type: "standard"
      activity_threshold: 0.92
      min_duration: 0.1
      end_threshold: 0.15
      dtc_threshold: 0
      gtc_threshold: 0
      # scenarios:
      #   buffer:
      #     start: 0
      #     end: 2
      #     step: 0.2
    #   isolate_events: True
      # plot_tag_repartition: False
      # PR_curve:
      #   variable: activity_threshold
      #   values:
      #     start: 0.02
      #     end: 0.10
      #     step: 0.05
    # - type: subsampling
    #   sample_step: 1
    #   activity_threshold: 0.6
    # - type: subsampling
    #   activity_threshold: 0.5
    #   gtc: 0.1
    #   scenarios:
    #     sample_step: 1
    #     event_method: "activity_max"
    # - type: phenology
    #   method: citynet
    #   activity_threshold: 0.5
    #   gtc: 0.1
    #   scenarios:
    #     sample_step: 1
    #     event_method: "activity_max"
    # - type: citynet
    #   activity_threshold: 0.5
    #   databases: ["citynet"]

      # event_method: activity_max
    #   PR_curve:
    #     variable: activity_threshold
    #     values:
    #       start: 0
    #       end: 0.98
    #       step: 0.02
    #   # event_method: "average"
    #   # tag_method: "proportion"
    #   gtc: 0.3
  # - type: "subsampling"
  #   gtc: 0.3
  #   scenarios:
  #     sample_step: [0.5, 1]
  #     event_threshold: [0.5, 0.95]
  #     event_method: ["average", "presence"]

############
## Models ##
############
models_options:
  model_dir: '/mnt/win/UMoncton/Doctorat/dev/dlbd/results/models/local/run2'
  # id: "{databases_options--spectrogram--n_mels}"
  # id_prefixes:
  #   databases_options--spectrogram--n_mels: "_nmels-"
  inference: True
  spectrogram_overlap: 0.95
  reclassify: False
  batch_size: 64


  
models:
  - name: "DLBD"
    class: "dlbd.models.dlbd.DLBD"
  # - name: "DLBDL_Ci"
  #   class: "dlbd.models.dlbd.DLBDLite"
  #   model_dir: "results/models/gpu/run3"


###############
## Databases ##
###############

databases: 
  - name: nips4b
  - name: citynet
  - name: full_summer1

databases_options:
  class_type: "biotic"
  spectrogram:
    n_mels: 32
    n_fft: 512
    sample_rate: "original"


  # - name: arctic_complete
  # - name: NABS
  # - name: nips4b
  #- name: NABS
  # - name: nips4b
    # scenarios:
    #     spectrogram:
    #       sample_rate: ["original", 22050]