parent_path: "config/runs/run1/parent.yaml"

data_config: "config/data/data_config.yaml"
clean_empty_models: True
skip_trained: True

logs:
  log_dir: "logs/gradient_tape/run1"
  use_version: True

# name : MODEL_NAME


suffix: "{databases_options--spectrogram--n_mels}_{n_epochs}"
suffix_prepend:
  databases_options--spectrogram--n_mels: "_nmels-"


##
## Model options
##

n_epochs: 20
learning_rate: 0.01
epoch_save_step: 5
# from_epoch: 100

learn_log: 0
do_augmentation: 1
A: 0.001 # biotic 
B: 10.0 #biotic
ensemble_members: 1
training_balanced: True
pixels_per_sec: 200

input_height: 32

batch_size: 64
do_batch_norm: 1
channels: 4
num_filters: 128
num_dense_units: 128
conv_filter_width: 4
wiggle_room: 5
dropout: 0.5

early_stopping:
  patience: 5
  min_delta: 0.002
  restore_best_weights: False

spectrogram_overlap: 0.75
random_start: True

time_mask: True
freq_mask: True

##
## Databases
##

databases: ["nips4b"]

databases_options:
  spectrogram:
    win_length: 512
    n_mels: 32
    sample_rate: "original"
    # to_db: True

scenarios:
  - name: "DLBD_nobal"
    class: "dlbd.models.dlbd.DLBD"
    training_balanced: False
    num_dense_units: 64
    num_dense_units2: 32
    # gt_prop: [0.10, 0]
    dilation_rate: [[[1, 2], 1]]
  - name: "DLBD"
    class: "dlbd.models.dlbd.DLBD"
    num_dense_units: 64
    num_dense_units2: 32
    # gt_prop: [0.10, 0]
    dilation_rate: [[[1, 2], 1]]
  - name: "DLBD_512_nobal"
    class: "dlbd.models.dlbd.DLBD"
    training_balanced: False
    num_dense_units: 512
    num_dense_units2: 256
    pixels_per_sec: 50
    # gt_prop: [0.10, 0]
    dilation_rate: [[[1, 2], 1]]

  # - name: "DLBD"
  #   suffix: "_dl{dilation_rate}"
  #   class: "dlbd.models.dlbd.DLBD"
  #   early_stopping: True
  #   num_dense_units: 128
  #   dilation_rate: [[[1, 2], 1]]

  # - name: "DLBD_ma"
  #   class: "dlbd.models.dlbd.DLBD"
  #   use_ma: True
  #   early_stopping: True
  #   num_dense_units: 128
  #   dilation_rate: [[[1, 2], 1]]

  # - name: "DLBD_swa"
  #   class: "dlbd.models.dlbd.DLBD"
  #   use_swa: True
  #   early_stopping: True
  #   num_dense_units: 128
  #   dilation_rate: [[[1, 2], 1]]

  # - name: "DLBD2"
  #   class: "dlbd.models.dlbd.DLBD2"
  #   early_stopping: True
  #   num_dense_units: 128
  #   dilation_rate: [[[1, 2], 1]]

  # - name: "DLBD2_swa"
  #   class: "dlbd.models.dlbd.DLBD2"
  #   use_swa: True
  #   early_stopping: True
  #   num_dense_units: 128

  # - name: "DLBD2_ma"
  #   class: "dlbd.models.dlbd.DLBD2"
  #   use_ma: True
  #   early_stopping: True
  #   num_dense_units: 128
  # # - name: "DLBD"
    # class: "dlbd.models.dlbd_test.DLBD" 
  # - name: "DLBDL_A"
  #   class: "dlbd.models.dlbd.DLBD"
  #   learning_rate: [[0.01], [0.001]]
  #   n_epochs: [[10], [20], [50]]
  # - name: "DLBDL_A2"
    # class: "dlbd.models.dlbd.DLBDLite"
  # - name: "DLBDL_CNN"
  #   class: "dlbd.models.dlbd.DLBDLite"
  #   num_dense_units: 128
  #   databases_options:
  #     spectrogram:
  #       n_fft: [512, 1024, 2048]
    # transfer_learning: True
    # n_epochs: 100
    # learning_rate: 0.001
    # # fine_tuning:
    # #   n_epochs: 20
    # #   learning_rate: 0.00001 
    # weights_opts:
    #     name: "DLBDL_Ci_nmels-32"
    #     model_dir: '/mnt/win/UMoncton/Doctorat/dev/dlbd/results/models/gpu/run3'


