data_config: "config/gpu/runs/trim/data_config.yaml"
parent_path: "config/gpu/runs/evaluation_parent.yaml"

models_options:
  spectrogram_overlap: 0.95
  reclassify: True

evaluators_options:
  draw_plots: False

evaluators:
  - type: "standard"
    activity_threshold: 0.9
    min_duration: 0.1
    end_threshold: 0.15
    dtc_threshold: 0
    gtc_threshold: 0
  - type: subsampling
    sample_step: 1
    event_method: "activity_max"
    activity_threshold: 0.5