data_config: "config/gpu/runs/trim/data_config.yaml"
parent_path: "config/gpu/runs/training_parent.yaml"

skip_trained: True

databases: ['citynet2', "nips4b2", "NABS2", "arctic_complete2"]

id: "_{learning_rate}_{n_epochs}"
id_prefixes:
  learning_rate: "lr-"
  n_epochs: "epochs-"

n_epochs: 50
learning_rate: 0.01
pixels_per_sec: 200
num_filters: 64
wiggle_room: 10
early_stopping:
  patience: 5
  min_delta: 0.005
spectrogram_overlap: 0.75
random_start: True
# regularizer:
#   type: "l2"
#   value: 0.001
# time_mask:
#   value: 20
# freq_mask:
#   value: 50
num_dense_units: 128
time_mask: False
freq_mask: False

scenarios:
  - name: "DLBDL_original_mask"
    id: "_tm{time_mask--value}-{time_mask--prop}_fm{freq_mask--value}-{freq_mask--prop}"
    class: "dlbd.models.dlbd.DLBD"
    time_mask:
      value: [30, 15]
      prop: [50, 70, 95]
    freq_mask:
      value: [100, 50]
      prop: [50, 70, 95]
  - name: "DLBD_3x3_nomask"
    id: "_dil{dilation_rate}"
    class: "dlbd.models.dlbd.DLBD"
    dilation_rate: [[1,2]]
    conv_filter_width: 3
    conv_filter_height: 3
  - name: "DLBD_3x3x2_nomask"
    class: "dlbd.models.dlbd.DLBD"
    id: "_dil{dilation_rate}"
    dilation_rate: [[1,2]]
    conv_filter_width: 3
    conv_filter_height: 3
    conv2_filter_width: 3
    conv2_filter_height: 3
  - name: "DLBD_c2-3x3_nomask"
    id: "_dil{dilation_rate}"
    class: "dlbd.models.dlbd.DLBD"
    dilation_rate: [[1,2]]
    conv2_filter_width: 3
    conv2_filter_height: 3
  - name: "DLBDL_original_nomask"
    id: "_patience{early_stopping--patience}_overlap{spectrogram_overlap}"
    class: "dlbd.models.dlbd.DLBD"




