data_config: "config/gpu/runs/trim/data_config.yaml"
parent_path: "config/gpu/runs/training_parent.yaml"

skip_trained: True

id: "_{learning_rate}_{n_epochs}"
id_prefixes:
  learning_rate: "lr-"
  n_epochs: "epochs-"

n_epochs: 15
learning_rate: 0.01
pixels_per_sec: 200

scenarios:
  - name: "DLBDL_mask"
    class: "dlbd.models.dlbd.DLBD"
    id: "_{num_dense_units}_wig-{wiggle_room}_nf-{num_filters}_pix{pixels_per_sec}"
    early_stopping:
      patience: 2
    random_start: True
    num_dense_units: 128
    num_filters: 64
    wiggle_room: 10
    pixels_per_sec: 200
    databases: [['citynet2', "nips4b2", "NABS2", "arctic_complete2"]]





