#* All path can be relative to the root_dir or complete
# root_dir: other dirs will be relative to this one
data_dir: 'wavs'
tags_dir: 'annotations'
training_dir: 'training'
validation_dir:  'validation'
test_dir: 'test'
dest_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/datasets'
save_intermediate: False

subfolders:
  - type: "spectrogram"
    options: ["sample_rate", "type", "n_fft", "win_length", "hop_length"]

data_extensions:
  - ".wav"
  - ".WAV"
recursive: True

#* Tags files options
tags:
  suffix: "-sceneRect.csv"
  columns:
    Label: "tag"
    Related: "related"
    LabelStartTime_Seconds: "tag_start"
    LabelEndTime_Seconds: "tag_end"
    overlap: "overlap"
    background: "background"
    noise: "noise"
  columns_type:
    overlap: "str"
  with_data: False


databases:
  #* All options found in data can be overriden in each iteration. If not found, default values
  #* from data will be used
    - name: 'warblr'
      root_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/raw/warblr/'
      tags_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/raw/warblr/test'
      generate_file_lists: True
      loader: "bad_challenge"
      db_types: ["test"]
    
spectrogram:
  type: "mel"
  n_mels: 32
  n_fft: 2048
  hop_length: 1024
  sample_rate: 22050 # For no resampling: remove option or set to original

class_type: "biotic"
classes_file: "src/classes.csv"