data_config: "config/gpu/runs/trim/data_config.yaml"
parent_path: "config/gpu/runs/training_parent.yaml"

skip_trained: True

databases: ['citynet2', "nips4b2", "NABS2", "arctic_complete2"]

suffix: "_{learning_rate}_{n_epochs}"
suffix_prepend:
  learning_rate: "lr-"
  n_epochs: "epochs-"

n_epochs: 50
learning_rate: 0.01
pixels_per_sec: 200
num_filters: 64
wiggle_room: 10
early_stopping:
  patience: 5
  min_delta: 0.002
spectrogram_overlap: 0.75
random_start: True
# regularizer:
#   type: "l2"
#   value: 0.001
# time_mask:
#   value: 20
# freq_mask:
#   value: 50
num_dense_units: 128
time_mask: True
freq_mask: True

scenarios:
  - name: "DLBDL_original_mask"
    suffix: "{num_dense_units}_{num_dense_units2}"
    class: "dlbd.models.dlbd.DLBD"
    num_dense_units: [128, 256, 512]
    num_dense_units2: [0, 32, 64, 128]
  - name: "DLBD_3x3_d128"
    suffix: "_dil{dilation_rate}"
    class: "dlbd.models.dlbd.DLBD"
    dilation_rate: [[1,2]]
    conv_filter_width: 3
    conv_filter_height: 3
  - name: "DLBD_3x3x2"
    class: "dlbd.models.dlbd.DLBD"
    suffix: "_dil{dilation_rate}"
    dilation_rate: [[1,2]]
    conv_filter_width: 3
    conv_filter_height: 3
    conv2_filter_width: 3
    conv2_filter_height: 3
  - name: "DLBD_c2-3x3"
    suffix: "_dil{dilation_rate}"
    class: "dlbd.models.dlbd.DLBD"
    dilation_rate: [[1,2]]
    conv2_filter_width: 3
    conv2_filter_height: 3
  # - name: "DLBDL_original_nomask"
  #   suffix: "_patience{early_stopping--patience}_overlap{spectrogram_overlap}"
  #   class: "dlbd.models.dlbd.DLBD"




