

data_config: "src/training_data_config_gpu.yaml"

model_dir: '/home/sylvain/data/results/models/'

name: "CityNetTF2_Dropout"
id: "resized"

id_prefixes:
  default: "_"
  version: "_v"

databases: ["arctic", "citynet"]

model: 
  max_epochs: 100
  from_epoch: 50
  # from_version: 3
  # from_epoch: 0
  epoch_save_step: 5
  learn_log: 0
  do_augmentation: 1
  A: 0.001 # biotic 
  B: 10.0 #biotic
  # # A: 0.025 # anthropic
  # # B: 2.0 # anthropic
  ensemble_members: 1
  training_balanced: True
  resize_spectrogram: True

net:
  batch_size: 128
  do_batch_norm: 1
  hww_x: 10
  hww_y: 10
  spec_height: 32
  channels: 4
  num_filters: 128
  num_dense_units: 512
  conv_filter_width: 4
  wiggle_room: 5
  learning_rate: 0.001
  dropout: 0.5

logs:
  log_dir: "/home/sylvain/logs/gradient_tape/"
  use_version: True


# scenarios:
#   - id: "{model--max_epochs}"
#     id_prefixes:
#       model--max_epochs: _nepoch-
#     databases_options:
#       spectrogram:
#           sample_rate: [22050, "original"]
#       # databases:
#       #   - name: "arctic"
#       #     spectrogram:
#       #       sample_rate: [22050, 16000]
#       #   - name: "ciytnet_small"
#       #     spectrogram:
#       #       sample_rate: [22050, 16000]
#     model:
#       max_epochs: [1, 5]
