#* All path can be relative to the root_dir or complete
# root_dir: other dirs will be relative to this one
data_dir: 'wavs'
tags_dir: 'annotations'
training_dir: 'training'
validation_dir:  'validation'
test_dir: 'test'
dest_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/datasets'
save_intermediate: False

use_subfolders: ["class", "spectrogram"]

audio_extensions:
  - ".wav"
  - ".WAV"
recursive: True


tags_suffix: "-sceneRect.csv"
tags_columns:
  Label: "tag"
  Related: "related"
  LabelStartTime_Seconds: "tag_start"
  LabelEndTime_Seconds: "tag_end"
  overlap: "overlap"
  background: "background"
  noise: "noise"
tags_columns_type:
  overlap: "str"




databases:
  #* All options found in data can be overriden in each iteration. If not found, default values
  #* from data will be used
  - name: 'citynet'
    root_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/citynet/CityNet'
    #db_types: ["validation", "training"]
  - name: 'arctic'
    root_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/citynet/Arctic'
    # overwrite: False
    # generate_file_lists: True
    #* split: Defines proportion of data to set aside for test and validation datasets.
    #* If provided, first the test dataset is set aside, then the remaining data is split into
    #* training and validation datasets.
    #* Overrides training_dir/validation_dir. Set to false or 0 to avoid using it in a database
    split:
      test: 0.2
      validation: 0.2
    # train_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/Arctic'
    data_dir: "/mnt/win/UMoncton/McGill University/Tommy O'Neill Sanger - Labeled Recordings"
    tags_with_data: True
    # tags_dir: '/mnt/win/UMoncton/Doctorat/data/dl_training/Arctic2/tags'
    
spectrogram:
  type: "mel"
  n_mels: 32
  n_fft: 2048
  hop_length: 1024

class_type: "biotic"
classes_file: "src/classes.csv"