
data_config: "src/data_config.yaml"
detectors: ["standard"]
predictions_dir: "results/predictions"
weights_dir: "results/models"


models:
  - name: "CityNetTF2"
    package: "dlbd.models.CityNetTF2"
    versions: [1,2,3]
    weights_dir: "results/models"