
data_config: "src/evaluation_data_config.yaml"
save_results: True #True

###########
## Paths ##
###########
predictions_dir: "results/predictions"
evaluation_dir: "results/evaluation"

###############
## Detectors ##
###############
detectors: 
  - type: "standard"
    min_activity: 0.95
    min_duration: 0.3
    end_threshold: 0.15
    dtc_threshold: 0.3
    gtc_threshold: 0.1
    isolate_events: True
  - type: "subsampling"
    scenarios:
      sample_step: [0, 1]
      event_threshold: [0.5, 0.95]

############
## Models ##
############
models_options:
  model_dir: "results/models"

models:
  # - name: "CityNetTF2_Dropout"
  #   package: "dlbd.models.CityNetTF2Dropout"
  #   class: "dlbd.models.CityNetTF2Dropout.CityNetTF2Dropout"
  - name: "CityNetOriginal"
    package: "dlbd.models.CityNetOriginal"
    class: "dlbd.models.CityNetOriginal.CityNetOriginal"
    version: 0
  - name: "CityNetTF2_Dropout_resized"
    class: "dlbd.models.CityNetTF2Dropout.CityNetTF2Dropout"
    version: 1
    scenarios:
      id: "{model--from_epoch}"
      id_prefixes:
        model--from_epoch: "_fe-"
      model:
        from_epoch: [30, 100]
  # - name: "CityNetTF2"
  #   id: "resize_spec_bicubic"
  #   package: "dlbd.audio.models.CityNetTF2"
  #   options:
  #     versions: [1]
  #     model:
  #       resize_spectrogram: True
  #       pixels_in_sec: 20
  #       rezise_method: bicubic
  # - name: "CityNetTF2"
  #   id: "resize_spec_bilinear"
  #   package: "dlbd.audio.models.CityNetTF2"
  #   options:
  #     model:
  #       versions: [1]
  #       resize_spectrogram: True
  #       pixels_in_sec: 20
  #       rezise_method: bilinear
  # - name: "CityNetTF2"
  #   id: "resize_spec_25pis"
  #   package: "dlbd.audio.models.CityNetTF2"
  #   versions: [1]
  #   options:
  #     model:
  #       resize_spectrogram: True
  #       pixels_in_sec: 25
  # - name: "CityNetTF2Dropout"
  #   package: "dlbd.models.CityNetTF2Dropout"
  #   versions: [1]
    #reclassify: True

###############
## Databases ##
###############

databases_options:
  scenarios:
    spectrogram:
      sample_rate: ["original", 22050]

databases:
  - name: citynet_small
    # scenarios:
    #     spectrogram:
    #       sample_rate: ["original", 22050]
  - name: arctic
    # scenarios:
    #     spectrogram:
    #       sample_rate: ["original", 22050]