
data_config: "src/data_config.yaml"
detectors: 
  - type: "standard"
    min_activity: 0.95
    min_duration: 0.3
    end_threshold: 0.15
    dtc_threshold: 0.3
    gtc_threshold: 0.1
    isolate_events: True
  - type: "subsampling"
    sample_step: 0
    event_threshold: 0.5
  - type: "subsampling"
    sample_step: 1
predictions_dir: "results/predictions"
weights_dir: "results/models"


models:
  - name: "CityNetTF2"
    package: "dlbd.models.CityNetTF2"
    versions: [1]
  - name: "CityNetOriginal"
    package: "dlbd.models.CityNetOriginal"
    versions: [0]
    #reclassify: True