
data_config: "config/data/data_config.yaml"
save_results: True #True

###########
## Paths ##
###########
predictions_dir: "results/predictions/run1"
evaluation_dir: "results/evaluation/run1"

###############
## Detectors ##
###############

evaluators_options:
  do_PR_curve: False
  plots: "overlap_duration_bar; detected_tags"
  draw_plots: False

evaluators: 
    - type: "standard"
      activity_threshold: 0.7
      min_duration: 0.1
      end_threshold: 0.15
      dtc_threshold: 0
      gtc_threshold: 0
      # scenarios:
      #   buffer:
      #     start: 0
      #     end: 2
      #     step: 0.2
    #   isolate_events: True
      # plot_tag_repartition: False
      # PR_curve:
      #   variable: activity_threshold
      #   values:
      #     start: 0.02
      #     end: 0.10
      #     step: 0.05
    # - type: subsampling
    #   sample_step: 1
    #   activity_threshold: 0.6
    #   PR_curve:
    #     variable: activity_threshold
    #     values:
    #       start: 0
    #       end: 0.98
    #       step: 0.02
    #   # event_method: "average"
    #   # tag_method: "proportion"
    #   gtc: 0.3
  # - type: "subsampling"
  #   gtc: 0.3
  #   scenarios:
  #     sample_step: [0.5, 1]
  #     event_threshold: [0.5, 0.95]
  #     event_method: ["average", "presence"]

############
## Models ##
############
models_options:
  model_dir: "results/models/local/run1"
  id: "{databases_options--spectrogram--n_mels}"
  id_prefixes:
    databases_options--spectrogram--n_mels: "_nmels-"
  inference: True


  
models:
  - name: "DLBDL_A2"
    class: "dlbd.models.dlbd.DLBDLite"
    scenarios:
      n_mels: 32
      pixels_per_sec: 200
      databases_options:
        spectrogram:
          hop_length: 128
          win_length: [512, 256]
  # - name: "DLBDL_Ci"
  #   class: "dlbd.models.dlbd.DLBDLite"
  #   model_dir: "results/models/gpu/run3"


###############
## Databases ##
###############

databases_options:
  class_type: "biotic"
  spectrogram:
    n_mels: 64
    sample_rate: "original"
    hop_length: 512

databases:
  - name: citynet
  # - name: arctic_complete
  # - name: NABS
  # - name: nips4b
  #- name: NABS
  # - name: nips4b
    # scenarios:
    #     spectrogram:
    #       sample_rate: ["original", 22050]