data_config: "config/gpu/runs/trim/data_config.yaml"
parent_path: "config/gpu/runs/training_parent.yaml"

skip_trained: True

databases: ['citynet2', "nips4b2", "NABS2", "arctic_complete2"]

id: "_{learning_rate}_{n_epochs}"
id_prefixes:
  learning_rate: "lr-"
  n_epochs: "epochs-"

n_epochs: 50
learning_rate: 0.01
pixels_per_sec: 200
num_filters: 64
wiggle_room: 10
early_stopping:
  patience: 5
  min_delta: 0.002
spectrogram_overlap: 0.75
random_start: True
# regularizer:
#   type: "l2"
#   value: 0.001
# time_mask:
#   value: 20
# freq_mask:
#   value: 50
num_dense_units: 128
num_dense_units2: 0
time_mask: True
freq_mask: True

scenarios:
  - name: "DLBDL"
    id: "_pat{early_stopping--patience}_delta{early_stopping--min_delta}"
    class: "dlbd.models.dlbd.DLBD"
    early_stopping:
      patience: [5, 8, 10]
      min_delta: [0, 0.001, 0.002]
  - name: "DLBDL"
    id: "_dl{dilation_rate}"
    class: "dlbd.models.dlbd.DLBD"
    dilation_rate: [[1, [1,2]], [[1,2], 1], [[1,2], [1,2]]]
  - name: "DLBDL_original"
    class: "dlbd.models.dlbd.DLBD"
  - name: "DLBDL_dl1-2_1_pat5_delta0"
    class: "dlbd.models.dlbd.DLBD"
    dilation_rate: [[[1,2], 1]]
    early_stopping:
      patience: 5
      min_delta: 0
  - name: "DLBDL_dl1-2_1"
    id: "_pat{early_stopping--patience}_restore{early_stopping--restore_best_weights}"
    class: "dlbd.models.dlbd.DLBD"
    dilation_rate: [[[1,2], 1]]
    early_stopping:
      patience: [5, 8]
      min_delta: 0.001
      restore_best_weights: [True, False]
  - name: "DLBDL_dl1-2_1"
    id: "_pat{early_stopping--patience}_restore{early_stopping--restore_best_weights}_delta{early_stopping--min_delta}"
    class: "dlbd.models.dlbd.DLBD"
    dilation_rate: [[[1,2], 1]]
    early_stopping:
      patience: [5,8]
      min_delta: [0.001, 0.002, 0.004]
      restore_best_weights: [True, False]
  - name: "DLBDL_replicate_1"
    class: "dlbd.models.dlbd.DLBD"
    dilation_rate: [[[1,2], 1]]
  - name: "DLBDL_replicate_2"
    class: "dlbd.models.dlbd.DLBD"
    dilation_rate: [[[1,2], 1]]
  - name: "DLBDL_replicate_3"
    class: "dlbd.models.dlbd.DLBD"
    dilation_rate: [[[1,2], 1]]
  - name: "DLBDL_replicate_4"
    class: "dlbd.models.dlbd.DLBD"
    dilation_rate: [[[1,2], 1]]
  - name: "DLBDL_replicate_5_regl2"
    class: "dlbd.models.dlbd.DLBD"
    dilation_rate: [[[1,2], 1]]
    regularizer:
      type: "l2"
      value: 0.001
  - name: "DLBDL_replicate_6_regl2"
    class: "dlbd.models.dlbd.DLBD"
    dilation_rate: [[[1,2], 1]]
    regularizer:
      type: "l2"
      value: 0.001
  - name: "DLBDL_replicate_6_regl2"
    class: "dlbd.models.dlbd.DLBD"
    dilation_rate: [[[1,2], 1]]
    regularizer:
      type: "l2"
      value: 0.001
  - name: "DLBDL_noes"
    class: "dlbd.models.dlbd.DLBD"
    dilation_rate: [[[1,2], 1]]
    early_stopping: False
  - name: "DLBDL_noes_2"
    class: "dlbd.models.dlbd.DLBD"
    dilation_rate: [[[1,2], 1]]
    early_stopping: False
  - name: "DLBDL_ma1"
    class: "dlbd.models.dlbd.DLBD"
    dilation_rate: [[[1,2], 1]]
    use_ma: True
  - name: "DLBDL_ma2"
    class: "dlbd.models.dlbd.DLBD"
    dilation_rate: [[[1,2], 1]]
    use_ma: True




