
data_config: "applications/challenges/evaluation_data_config.yaml"
save_results: False #True

###########
## Paths ##
###########
predictions_dir: "applications/challenges/results/predictions"
evaluation_dir: "applications/challenges/results/evaluation"
models_options:
  spectrogram_overlap: 0.95
  reclassify: False

evaluators_options:
  draw_plots: False

evaluators:
  - type: "bad_challenge"
    method: "standard"
    activity_threshold: 0.9
    min_duration: 0.1
    end_threshold: 0.15
    dtc_threshold: 0
    gtc_threshold: 0
  # - type: subsampling
  #   sample_step: 1
  #   event_method: "activity_max"
  #   activity_threshold: 0.5
  # - type: citynet
  #   activity_threshold: 0.5

databases_options:
  class_type: "biotic"
  spectrogram:
    n_mels: 32
    sample_rate: "original"

databases:
  # - name: citynet_small
    # scenarios:
    #     spectrogram:
    #       sample_rate: ["original", 22050]
  # - name: arctic
  - name: warblr
#  - name: citynet
  # - name: nips4b
    # scenarios:
    #     spectrogram:
    #       sample_rate: ["original", 22050]