A: 0.001
B: 10.0
CONV_FILTER_WIDTH: 4
DO_BATCH_NORM: 1
HWW_X: 10
HWW_Y: 10
LEARN_LOG: 0
NUM_DENSE_UNITS: 512
NUM_FILTERS: 128
WIGGLE_ROOM: 5
annotations_dir: annotations
audio_dir: wavs
base_dir: /mnt/win/UMoncton/Doctorat/data/acoustic/reference/CityNet/
channels: 4
classname: biotic
conv_filter_width: 4
dest_dir: extracted
do_augmentation: 1
do_batch_norm: 1
dropout: 0.5
ensemble_members: 1
hww_x: 10
hww_y: 10
learn_log: 0
learning_rate: 0.001
max_epochs: 5
model_dir: /mnt/win/UMoncton/Doctorat/dev/ecosongs/src/test/citynet2/models/
model_name: citynet_augmented1
num_dense_units: 512
num_filters: 128
overwrite: true
root_dirs:
- /mnt/win/UMoncton/Doctorat/data/dl_training/citynet/CityNet
- /mnt/win/UMoncton/Doctorat/data/dl_training/citynet/Arctic
run_type: test_citynet
spec_height: 32
spec_type: mel
test_dir: test
train_dir: train
validation_split: 0.3
wiggle_room: 5
